# Generated by Django 2.1.4 on 2019-01-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_title',
            new_name='comment_time',
        ),
    ]
